In [1]:
from convokit import Corpus, download
import os.path

corpus = Corpus(filename = os.path.join(os.path.expanduser("~"), ".convokit/saved-corpora/new-2019"))

FileNotFoundError: [Errno 2] No such file or directory: '/Users/jeeyonkang/.convokit/saved-corpora/new_corpus_2019'

In [2]:
corpus.get_speakers_dataframe()

                     vectors             meta.name meta.type
id
j__john_g_roberts_jr      []  John G. Roberts, Jr.         J
shay_dvoretzky            []        Shay Dvoretzky         A
j__clarence_thomas        []       Clarence Thomas         J
j__elena_kagan            []           Elena Kagan         J
j__amy_coney_barrett      []     Amy Coney Barrett         J
...                      ...                   ...       ...
jean-claude_andre         []     Jean-Claude Andre         A
theane_d_evangelis        []   Theane D. Evangelis         A
e_joshua_rosenkranz       []  E. Joshua Rosenkranz         A
eric_t_lee                []           Eric T. Lee         A
henry_c_whitaker          []     Henry C. Whitaker         A

[105 rows x 3 columns]

In [3]:
corpus.get_conversations_dataframe()

,vectors,meta.id,meta.case_id,meta.advocates,meta.votes_side,meta.win_side
id,,,,,,
25478,[],25478,2023_22-340,"{'Shay Dvoretzky': {'id': 'shay_dvoretzky', 'n...","{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25479,[],25479,2023_22-448,{'Elizabeth B. Prelogar': {'id': 'elizabeth_b_...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25480,[],25480,2023_22-429,{'Adam G. Unikowsky': {'id': 'adam_g_unikowsky...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25482,[],25482,2023_22-660,"{'Easha Anand': {'id': 'easha_anand', 'name': ...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25481,[],25481,2023_22-500,"{'Jeffrey B. Wall': {'id': 'jeffrey_b_wall', '...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25483,[],25483,2023_22-807,"{'John M. Gore': {'id': 'john_m_gore', 'name':...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25485,[],25485,2023_22-585,"{'Shay Dvoretzky': {'id': 'shay_dvoretzky', 'n...","{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25487,[],25487,2023_22-611,"{'Allon Kedem': {'id': 'allon_kedem', 'name': ...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25486,[],25486,2023_22-324,{'Hashim M. Mooppan': {'id': 'hashim_m_mooppan...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25495,[],25495,2023_22-704,{'Malcolm L. Stewart': {'id': 'malcolm_l_stewa...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25490,[],25490,2023_22-846,{'Benjamin W. Snyder': {'id': 'benjamin_w_snyd...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25493,[],25493,2023_22-915,{'Elizabeth B. Prelogar': {'id': 'elizabeth_b_...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25496,[],25496,2023_22-888,"{'Misha Tseytlin': {'id': 'misha_tseytlin', 'n...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25503,[],25503,2023_22-193,"{'Brian Wolfman': {'id': 'brian_wolfman', 'nam...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25560,[],25560,2023_22-451,"{'Paul D. Clement': {'id': 'paul_d_clement', '...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25561,[],25561,2023_22-1219,"{'Roman Martinez': {'id': 'roman_martinez', 'n...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25499,[],25499,2023_22-666,"{'Jaime A. Santos': {'id': 'jaime_a_santos', '...","{'j__john_g_roberts_jr': 0, 'j__clarence_thoma...",1.0
25556,[],25556,2023_22-674,{'Charles L. McCloud': {'id': 'charles_l_mcclo...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25498,[],25498,2023_22-721,{'Richard A. Simpson': {'id': 'richard_a_simps...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25502,[],25502,2023_22-800,{'Andrew M. Grossman': {'id': 'andrew_m_grossm...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25497,[],25497,2023_22-6389,"{'Jeffrey T. Green': {'id': 'jeffrey_t_green',...","{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25501,[],25501,2023_23-124,"{'Curtis E. Gannon': {'id': 'curtis_e_gannon',...","{'j__john_g_roberts_jr': 0, 'j__clarence_thoma...",1.0
25555,[],25555,2023_22-1178,"{'Sopan Joshi': {'id': 'sopan_joshi', 'name': ...","{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25553,[],25553,2023_22-1074,"{'Paul J. Beard II': {'id': 'paul_j_beard_ii',...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25554,[],25554,2023_22-1238,{'Masha G. Hansford': {'id': 'masha_g_hansford...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25552,[],25552,2023_22-899,"{'Hari Santhanam': {'id': 'hari_santhanam', 'n...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25558,[],25558,2023_22-1165,"{'Linda T. Coberly': {'id': 'linda_t_coberly',...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25559,[],25559,2023_22-913,{'Robert J. McNamara': {'id': 'robert_j_mcnama...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25607,[],25607,2023_22-1008,"{'Bryan K. Weir': {'id': 'bryan_k_weir', 'name...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25606,[],25606,2023_23-51,{'Jennifer D. Bennett': {'id': 'jennifer_d_ben...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25610,[],25610,2023_23A349,{'Mathura J. Sridharan': {'id': 'mathura_j_sri...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25608,[],25608,2023_22-1078,{'Kannon K. Shanmugam': {'id': 'kannon_k_shanm...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25614,[],25614,2023_22-7386,{'Steven Y. Yurowitz': {'id': 'steven_y_yurowi...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25620,[],25620,2023_22-529,{'Jonathan E. Taylor': {'id': 'jonathan_e_tayl...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25619,[],25619,2023_22-976,{'Brian H. Fletcher': {'id': 'brian_h_fletcher...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25618,[],25618,2023_23-3,{'Jessica L. Ellsworth': {'id': 'jessica_l_ell...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25623,[],25623,2023_23-411,{'Brian H. Fletcher': {'id': 'brian_h_fletcher...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25622,[],25622,2023_22-842,"{'David D. Cole': {'id': 'david_d_cole', 'name...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25621,[],25621,2023_23-14,{'Jeffrey L. Fisher': {'id': 'jeffrey_l_fisher...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25624,[],25624,2023_22-1079,"{'Allyson N. Ho': {'id': 'allyson_n_ho', 'name...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25625,[],25625,2023_22-1025,"{'Anya A. Bidwell': {'id': 'anya_a_bidwell', '...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25626,[],25626,2023_22O141,"{'Frederick Liu': {'id': 'frederick_liu', 'nam...","{'j__john_g_roberts_jr': 1, 'j__anthony_m_kenn...",1.0
25629,[],25629,2023_23-250,{'Caroline A. Flynn': {'id': 'caroline_a_flynn...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25628,[],25628,2023_23-21,"{'Joshua P. Davis': {'id': 'joshua_p_davis', '...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25632,[],25632,2023_23-235,{'Elizabeth B. Prelogar': {'id': 'elizabeth_b_...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25631,[],25631,2023_23-370,{'Jeffrey L. Fisher': {'id': 'jeffrey_l_fisher...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25630,[],25630,2023_23-146,{'Kannon K. Shanmugam': {'id': 'kannon_k_shanm...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25636,[],25636,2023_23-108,"{'Lisa S. Blatt': {'id': 'lisa_s_blatt', 'name...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25634,[],25634,2023_23-50,"{'Easha Anand': {'id': 'easha_anand', 'name': ...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25635,[],25635,2023_23-5572,"{'Jeffrey T. Green': {'id': 'jeffrey_t_green',...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25637,[],25637,2023_22-982,"{'Jason D. Lewis': {'id': 'jason_d_lewis', 'na...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25641,[],25641,2023_23-175,{'Theane D. Evangelis': {'id': 'theane_d_evang...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25639,[],25639,2023_22-1218,"{'Daniel L. Geyser': {'id': 'daniel_l_geyser',...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25642,[],25642,2023_23-334,"{'Curtis E. Gannon': {'id': 'curtis_e_gannon',...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25643,[],25643,2023_23-367,"{'Lisa S. Blatt': {'id': 'lisa_s_blatt', 'name...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25612,[],25612,2023_22-277,{'Henry C. Whitaker': {'id': 'henry_c_whitaker...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25613,[],25613,2023_22-555,"{'Paul D. Clement': {'id': 'paul_d_clement', '...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0

In [4]:
corpus.get_utterances_dataframe()

,timestamp,text,speaker,reply_to,conversation_id,meta.id,meta.text,meta.speaker,meta.convo_id,meta.case_id,meta.speaker_type,meta.side,meta.start_times,meta.stop_times,meta.timestamp,meta.reply_to,vectors
id,,,,,,,,,,,,,,,,,
25478__1_001,0.17,We will hear argument this morning in Case 22-...,j__john_g_roberts_jr,,25478,25478__1_001,We will hear argument this morning in Case 22-...,"John G. Roberts, Jr.",25478,2023_22-340,J,,['0.17'],['7.42000005'],0.17,,[]
25478__1_002,7.42000005,"Mr. Chief Justice, and may it please the Court...",shay_dvoretzky,,25478,25478__1_002,"Mr. Chief Justice, and may it please the Court...",Shay Dvoretzky,25478,2023_22-340,A,1,"['7.42000005', '18.02', '23.565', '27.9', '37....","['18.02', '23.565', '27.9', '37.16500005', '44...",7.42000005,,[]
25478__1_003,131.845,"From your argument, it appears you do not acce...",j__clarence_thomas,,25478,25478__1_003,"From your argument, it appears you do not acce...",Clarence Thomas,25478,2023_22-340,J,,['131.845'],['143.325'],131.845,,[]
25478__1_004,143.325,"Not in this context, Justice Thomas, not -- no...",shay_dvoretzky,,25478,25478__1_004,"Not in this context, Justice Thomas, not -- no...",Shay Dvoretzky,25478,2023_22-340,A,1,['143.325'],['152.44'],143.325,,[]
25478__1_005,152.44,In what context can it have a distributive mea...,j__clarence_thomas,,25478,25478__1_005,In what context can it have a distributive mea...,Clarence Thomas,25478,2023_22-340,J,,['152.44'],['157.39'],152.44,,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25613__3_144,4609.855,"Yes, Your Honor.",aaron_l_nielson,,25613,25613__3_144,"Yes, Your Honor.",Aaron L. Nielson,25613,2023_22-555,A,0,['4609.855'],['4610.805'],4609.855,,[]
25613__3_145,4610.805,Thank you.,j__ketanji_brown_jackson,,25613,25613__3_145,Thank you.,Ketanji Brown Jackson,25613,2023_22-555,J,,['4610.805'],['4611.89'],4610.805,,[]
25613__3_146,4611.89,"Thank you, counsel. Rebuttal, Mr. Clement?",j__john_g_roberts_jr,,25613,25613__3_146,"Thank you, counsel. Rebuttal, Mr. Clement?","John G. Roberts, Jr.",25613,2023_22-555,J,,"['4611.89', '4613.38']","['4613.38', '4615.225']",4611.89,,[]
25613__4_001,4615.225,"Thank you, Mr. Chief Justice. Just a few point...",paul_d_clement,,25613,25613__4_001,"Thank you, Mr. Chief Justice. Just a few point...",Paul D. Clement,25613,2023_22-555,A,1,"['4615.225', '4616.71', '4618.16', '4620', '46...","['4616.71', '4618.16', '4620', '4624.56', '462...",4615.225,,[]
25613__4_002,4802.28,"Thank you, counsel, all counsel. The case is s...",j__john_g_roberts_jr,,25613,25613__4_002,"Thank you, counsel, all counsel. The case is s...","John G. Roberts, Jr.",25613,2023_22-555,J,,"['4802.28', '4804.02']","['4804.02', '0']",4802.28,,[]