This is a test for the usability of the corpus after scraping the data with the following command: 

```
python script.py --start_year 2020 --end_year 2020
```

In [13]:
from convokit import Corpus, download
import os.path

Trying to follow this, https://convokit.cornell.edu/documentation/corpus.html

In [ ]:
# This doesn't work... 
#corpus = Corpus(filename = os.path.expanduser("~")+"/Supreme-Court-Dataset-Extended/scripts/output/2020/")

In [35]:
# This works but doesn't load metadata
#corpus = Corpus(filename = os.path.expanduser("~")+"/Supreme-Court-Dataset-Extended/scripts/output/2020/utterance_info.jsonl")

In [26]:
# Now trying after unzipping what's in data
corpus = Corpus(filename = os.path.expanduser("~")+"/Supreme-Court-Dataset-Extended/data/supreme-2020/")

In [27]:
corpus.get_speakers_dataframe()

                     vectors              meta.name meta.type
id
j__john_g_roberts_jr      []   John G. Roberts, Jr.         J
michael_w_mcconnell       []   Michael W. McConnell         A
j__clarence_thomas        []        Clarence Thomas         J
j__stephen_g_breyer       []      Stephen G. Breyer         J
j__samuel_a_alito_jr      []   Samuel A. Alito, Jr.         J
...                      ...                    ...       ...
andrew_l_adler            []        Andrew L. Adler         A
adam_k_mortara            []        Adam K. Mortara         A
m_allison_guagliardo      []  M. Allison Guagliardo         A
jonathan_y_ellis          []      Jonathan Y. Ellis         A
jeremy_m_feigenbaum       []   Jeremy M. Feigenbaum         A

[113 rows x 3 columns]

In [33]:
corpus.get_conversations_dataframe().head(10)

,vectors,meta.id,meta.case_id,meta.advocates,meta.votes_side,meta.win_side
id,,,,,,
25279,[],25279,2020_19-309,{'Michael W. McConnell': {'id': 'michael_w_mcc...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25256,[],25256,2020_19-71,{'Edwin S. Kneedler': {'id': 'edwin_s_kneedler...,"{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25233,[],25233,2020_18-540,{'Nicholas J. Bronni': {'id': 'nicholas_j_bron...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25278,[],25278,2020_19-368,"{'Sean Marotta': {'id': 'sean_marotta', 'name'...","{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25236,[],25236,2020_18-956,{'Thomas C. Goldstein': {'id': 'thomas_c_golds...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25277,[],25277,2020_19-357,"{'Craig Goldblatt': {'id': 'craig_goldblatt', ...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25235,[],25235,2020_19-108,"{'Jeffrey B. Wall': {'id': 'jeffrey_b_wall', '...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25275,[],25275,2020_19-292,"{'Kelsi B. Corkran': {'id': 'kelsi_b_corkran',...","{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0
25248,[],25248,2020_19-438,"{'Brian P. Goldman': {'id': 'brian_p_goldman',...","{'j__john_g_roberts_jr': -1, 'j__clarence_thom...",-1.0
25232,[],25232,2020_19-547,{'Matthew Guarnieri': {'id': 'matthew_guarnier...,"{'j__john_g_roberts_jr': 1, 'j__clarence_thoma...",1.0

In [34]:
corpus.get_utterances_dataframe().head(10)

,timestamp,text,speaker,reply_to,conversation_id,meta.id,meta.text,meta.speaker,meta.convo_id,meta.case_id,meta.speaker_type,meta.side,meta.start_times,meta.stop_times,meta.timestamp,meta.reply_to,vectors
id,,,,,,,,,,,,,,,,,
25279__1_001,0.155,"Our first case today is Number 19-309, John Ca...",j__john_g_roberts_jr,,25279,25279__1_001,"Our first case today is Number 19-309, John Ca...","John G. Roberts, Jr.",25279,2020_19-309,J,,['0.155'],['8.605'],0.155,,[]
25279__1_002,8.605,"MR. McCONNELL: Mr. Chief Justice, and may it p...",michael_w_mcconnell,,25279,25279__1_002,"MR. McCONNELL: Mr. Chief Justice, and may it p...",Michael W. McConnell,25279,2020_19-309,A,1,"['8.605', '51.165', '91.125', '94.45', '119.06']","['51.165', '91.125', '94.45', '119.06', '131.5...",8.605,,[]
25279__1_003,131.585,"Well, Mr. McConnell, I'd like to begin with th...",j__john_g_roberts_jr,,25279,25279__1_003,"Well, Mr. McConnell, I'd like to begin with th...","John G. Roberts, Jr.",25279,2020_19-309,J,,['131.585'],['154.05'],131.585,,[]
25279__1_004,154.05,MR. McCONNELL: He -- he shows by his actions t...,michael_w_mcconnell,,25279,25279__1_004,MR. McCONNELL: He -- he shows by his actions t...,Michael W. McConnell,25279,2020_19-309,A,1,['154.05'],['177.98'],154.05,,[]
25279__1_005,177.98,"Well, I don't think that's applicable. The con...",j__john_g_roberts_jr,,25279,25279__1_005,"Well, I don't think that's applicable. The con...","John G. Roberts, Jr.",25279,2020_19-309,J,,"['177.98', '180.66', '185.14']","['180.66', '185.14', '197.12']",177.98,,[]
25279__1_006,197.12,"MR. McCONNELL: Well, Mr. Chief Justice, he -- ...",michael_w_mcconnell,,25279,25279__1_006,"MR. McCONNELL: Well, Mr. Chief Justice, he -- ...",Michael W. McConnell,25279,2020_19-309,A,1,"['197.12', '205.3']","['205.3', '210.095']",197.12,,[]
25279__1_007,210.095,"Well, he also said that he would consider and ...",j__john_g_roberts_jr,,25279,25279__1_007,"Well, he also said that he would consider and ...","John G. Roberts, Jr.",25279,2020_19-309,J,,"['210.095', '216.17']","['216.17', '221.52']",210.095,,[]
25279__1_008,221.52,"MR. McCONNELL: Well, he did not, in fact, appl...",michael_w_mcconnell,,25279,25279__1_008,"MR. McCONNELL: Well, he did not, in fact, appl...",Michael W. McConnell,25279,2020_19-309,A,1,['221.52'],['230.12500005'],221.52,,[]
25279__1_009,230.12500005,Is there anything else he has to do? He -- he ...,j__john_g_roberts_jr,,25279,25279__1_009,Is there anything else he has to do? He -- he ...,"John G. Roberts, Jr.",25279,2020_19-309,J,,"['230.12500005', '236.76']","['236.76', '239.09']",230.12500005,,[]
25279__1_010,239.09,"MR. McCONNELL: His -- actually, even his alleg...",michael_w_mcconnell,,25279,25279__1_010,"MR. McCONNELL: His -- actually, even his alleg...",Michael W. McConnell,25279,2020_19-309,A,1,"['239.09', '252.79', '256.69', '265.18']","['252.79', '256.69', '265.18', '322.32']",239.09,,[]

In [37]:
# Let's try iterating thru the utterances now 
# As in https://github.com/kakeith/interruptions-supreme-court/blob/main/scripts/create_analyze_chunks.py#L53
all_utt = corpus.get_utterance_ids()
for i, utt in enumerate(corpus.iter_utterances()):
    case_id = utt.meta['case_id']
    speaker_name = utt.speaker.meta['name'].replace(',', '')
    print(case_id, speaker_name)
    break

2020_19-309 John G. Roberts Jr.